### ISSUE TITLE
Routes with different variables on the same level do not work

### ISSUE THREAD

**Issue by ahx** [aristotelesbr/lennarb#53]
Hi,

I noticed that when adding routes with dynamic and static fields on the same level the trie get's confused:

```ruby
	router = Lennarb::RouteNode.new
	router.add_route(['foo', ':foo'], 'GET', proc { 'foo' })
	router.add_route(%w[foo special], 'GET', proc { 'special' })
	router.add_route(['foo', ':id', 'bar'], 'GET', proc { 'bar' })

	_, params = router.match_route(%w[foo 23], 'GET')
	assert_equal({ foo: '23' }, params) # Fails because params are {:id=>"23"} instead of {:foo=>"23"}
```

I have added a [PR to illustrate this](https://github.com/aristotelesbr/lennarb/pull/52).

This is the [same problem hanami-router has](https://github.com/hanami/router/issues/255).

Thanks for publishing this gem. I think it's super nice.

**Comment by aristotelesbr** [comment]
Hi @ahx! Thank you for reporting this issue. I really appreciate your feedback and the PR you submitted to illustrate the problem. I'll take a look and try to fix the trie behavior. Any suggestions? 😄

**Comment by ahx** [comment]
Hi. I did not find a way to solve this so far. It’s not an easily solved problem. Others have struggled with this before and failed.

**Comment by aristotelesbr** [comment]
Hi @ahx,

I'm not entirely sure, but this https://github.com/aristotelesbr/lennarb/pull/54 might address the issue you reported here.

Let me know if you get a chance to test it! 🙃

**Comment by ahx** [comment]
Hey @aristotelesbr. Thanks for looking into that. The [test is green](https://github.com/aristotelesbr/lennarb/pull/54/files#diff-2517d2de4350cd4ebdee8d291fdc7bf3a5293fbdec1160a0289ee4eb122fa53dR45-R60), so I think you solved the issue. Nice work!

**Comment by ahx** [comment]
Something not related to this issue: The reason I am interested in all this is, because I am looking for a small, fast routing library to use in [openapi_first](https://github.com/ahx/openapi_first). I wish we would have a de-facto default library/gem to use in Ruby where people can build their own micro/midi/macro framework on top off. Lennarb's route_node.rb looks like a good candidate for that.
